install.packages("parsedate", repos = "https://cloud.r-project.org/")
install.packages("reshape2", repos = "https://cloud.r-project.org/")
install.packages("ggplot2", repos = "https://cloud.r-project.org/")
install.packages("gdtools", repos = "https://cloud.r-project.org/")
install.packages("svglite", repos = "https://cloud.r-project.org/")
quit()
